[package]
name = "lazy_thread_local"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(target_family="unix")'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "windows")'.dependencies]
libc = "0.2"
winapi = {version="0.3", features=["fibersapi"]}